name = "GoldGates"
uuid = "6beb795d-11fa-411e-af76-5aa8f71e9b96"
version = "0.0.1"

[deps]
AMO = "84f1a4cc-bedd-412d-9d4a-321e40b84e6a"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
MSSim = "bb1f6ef4-bfb3-4e09-8d02-eba6158954f3"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProtoBuf = "3349acd9-ac6a-5e09-bcdb-63829b23a429"

[sources]
AMO = {rev = "master", url = "https://github.com/yuyichao/AMO.jl"}
MSSim = {rev = "main", url = "https://github.com/euriqa-brassboard/MSSim.jl.git"}

[compat]
AMO = "0.1.0"
JSON = "0.21"
MSSim = "1.0"
NLopt = "1.1"
Printf = "1.11"
ProtoBuf = "1.0"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
